### ISSUE TITLE
NPM postinstall script fails on Microsoft Windows

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#1]
The npm postinstall script is defined for Unix-based systems. The path separator used is incompatible with Windows systems. But Windows' path separator is incompatible with Unix systems. 

Heroku's default Node.js buildpack only runs: 

```
$ npm install 
```

Therefore the postinstall script is required to obtain bower components on Heroku, which runs Ubuntu Linux. 

On Windows systems, run: 

```
$ npm install
# npm -g install bower
$ bower install
```

Ignore the npm errors that may occur.

**Comment by aneesh-neelam** [comment]
Somehow I fixed this for Microsoft Windows as well :-P

**Comment by baishali-ghosh** [comment]
Yaaay. You're a smartass
