### ISSUE TITLE
Query - Support for (Integrated 5 year) 15-16 batch?

### ISSUE THREAD

**Issue by VinayGupta23** [aneesh-neelam/VITacademics#100]
_Feedback for the Windows Phone App (as of 10th July 2015):_
"Whenever I'm trying to login to my student account, it shows an "unknown error". I'm a student in VIT Vellore enrolled in MTech Software Engineering Integrated (5 years program). Kindly solve this issue as quickly as possible. This issue is not only with me but with **all my friends and roommates of 2015-16 batch**."

Have verified from user that he is running the latest stable version of the app. Also, some of my friends from Integrated 5 year software 2013-14 batch can use the app without any issues.

Is there any known format that was changed for the 15-16 batch? Or am I missing something crazy?
Also if anyone could check with the server or other client apps for someone from **Integrated 5 year 15-16 batch**.

User has refused to share credentials for the sake of fixing. If anyone can provide credentials of _anyone_ from 15-16 batch, please send it to me.

**Comment by aneesh-neelam** [comment]
You mean M.S. Software Engineering, 5 year integrated program? I thought that works fine?

**Comment by VinayGupta23** [comment]
Well he said MTech. Does VIT give MS or MTech for 5 year integrated?
Yeah, it does. That's why I can't understand this.

Well, to make sure where the problem exactly is, we need to check first with other B.Tech students of 15-16. So credentials are needed. Also, we need some students from M.Tech.

P.S. And hey its a century of issues :P
Cheers! :P

**Comment by ayushagarwal95** [comment]
Could you ask him to send over his credentials through mail to me?

**Comment by VinayGupta23** [comment]
I told you, he refused. I told him its only for fixing the issue. And I just mentioned that if he can, he can get me credentials of his friends also. But right now, he isn't providing.

If you've spoken to any first years, try getting theirs. Also if you know any first year with a windows phone, please ask him if it the app works... That would be helpful.

**Comment by ayushagarwal95** [comment]
Well, I will try and find out if I can.

**Comment by aneesh-neelam** [comment]
Need first year credentials. @ayushagarwal95, get some from the database and post on Slack.
