### ISSUE TITLE
Invalid Credentials encountered for First Years

### ISSUE THREAD

**Issue by ayushagarwal95** [aneesh-neelam/VITacademics#101]
First year credentials are being returned as invalid when trying to login through the API Server, whereas it is logging in if we use the Parent Login Website.

**Comment by aneesh-neelam** [comment]
Oh, for god's sake. :-(

**Comment by VinayGupta23** [comment]
Damn.
Is this the same problem as #100?

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Maybe.

**Comment by ayushagarwal95** [comment]
It's occurring for 15 year credentials from whatever I have tested.

**Comment by aneesh-neelam** [comment]
I'll check it out tomorrow. Send me some first year credentials on Slack.

**Comment by VinayGupta23** [comment]
Please send me one or two credentials as well. I want to check how its being handled by the app.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
@VinayGupta23: You should just get incorrect credentials, not letting the user login in the first place. And check Slack for credentials.
