### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#112]
@ayushagarwal95: Figure out why the tests are failing, and fix them.

**Comment by ayushagarwal95** [comment]
Done.

**Comment by aneesh-neelam** [comment]
This is dumb. Implement #32, and remove all these timeouts, including for mocha.

**Comment by ayushagarwal95** [comment]
That is a whole lot dependent on @karthikb351 being free.
