### ISSUE TITLE
500 internal server error 

### ISSUE THREAD

**Issue by kp96** [aneesh-neelam/VITacademics#117]
I was facing 500 internal server errors even with simple api calls like

```
var unirest = require('unirest');
var url = 'https://vitacademics-rel.herokuapp.com/api/v2/vellore/login';
var data = {regno : "some_value", dob : "some_value", mobile: "some_value"}
unirest.post(url).send(data).end(function(response) {
        console.log(response.body);
})

```

Turns out that it is an issue due to one of your api's dependency `node-ga`mentioned [here](https://github.com/gthole/node-ga/commit/01e775c5b125b44ec5e6d4bc18d4259b17aeedfb). I have applied the fix on my side and it worked. Please consider fixing it or update the documentation to include `user-agent header`.

**Comment by aneesh-neelam** [comment]
@kp96: Please issue Pull Request against the development branch. @ayushagarwal95: Check and merge.

**Comment by aneesh-neelam** [comment]
Oh wait, sorry. @ayushagarwal95: Update the dependencies.

**Comment by ayushagarwal95** [comment]
Running a npm-check gave me an update only for the dependency momentz-timezone and not node-ga. The dependency node-ga is up to date at version 0.1.1.

**Comment by kp96** [comment]
You need to explicitly change the code according to the fix mentioned above. They haven't released it after the fix I guess.

**Comment by ayushagarwal95** [comment]
We will have to wait for the update in that case.
