### ISSUE TITLE
Bad status despite correctly parsed data in JSON

### ISSUE THREAD

**Issue by VinayGupta23** [aneesh-neelam/VITacademics#118]
On refreshing for several clients, the JSON has a status relating to server error, despite having the data parsed and populated correctly (ignoring #116 of course).

This is leading to a "server error" message for the clients and has been found to be an issue since October at least.
Please fix these errors ASAP.

The entire file: [ErrorData.txt](https://github.com/aneesh-neelam/VITacademics/files/78112/ErrorData.txt)

P.S. The file was renamed to `.txt` for uploading. Also, credentials of the user have been deliberately removed, since I have not asked the user if it can be shared publicly.

**Comment by aneesh-neelam** [comment]
Oh, for god's sake. @ayushagarwal95: Move the database to DigitalOcean.

**Comment by VinayGupta23** [comment]
If I understand correctly, is this occurring because the data is scraped successfully from the site, but a write to the MongoDB fails?

**Comment by ayushagarwal95** [comment]
Yes, the connections between the API server and 5 instances of MongoDB are unstable.

**Comment by VinayGupta23** [comment]
In that case, if a migrate is not feasible at the moment in a very short period of time, I suggest that the status should still read "Success" since the data IS available.

What has really failed is the internal caching technique to reduce VIT load, which is not a failure for the client.

Also, since there is only a small set of people who regularly face this issue, it shouldn't be a problem with load.

...
And how does this explain that a very particular set of people ONLY face this issue?

**Comment by ayushagarwal95** [comment]
The 5 different instances are for the students in different years respectively. So if a particular connection goes down, that set of people receive the error.

**Comment by VinayGupta23** [comment]
That is not the case that clients are facing.

I have a very specific set of people who have forever faced this issue no matter what. And the rest have effectively never faced it.

Remember the other guy I told you about on WhatsApp. Same issue I believe. And only him.

Which is weird.

**Comment by ayushagarwal95** [comment]
The migration process is almost done with, just needs testing.

**Comment by aneesh-neelam** [comment]
What's the problem here again?

**Comment by ayushagarwal95** [comment]
The migration is done. @VinayGupta23 Do check whether the same user faces the same issue now. Also, do ask the set of people who were facing the issue since always.

**Comment by ayushagarwal95** [comment]
@VinayGupta23 , if the errors for those users have been fixed, then this issue is also fixed.

**Comment by VinayGupta23** [comment]
Im waiting for feedback from them.
Ill close the issue after they revert.

Sent from my Windows Phone

**Comment by VinayGupta23** [comment]
I think the errors have been fixed.

And just a side note, in general, if scraping succeeds and database write fails, don't return an error. (if this is being done).

**Comment by aneesh-neelam** [comment]
@VinayGupta23: That is being done. And no, the database needs to be consistent.
