### ISSUE TITLE
Friends Sharing API

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#13]
I'll be changing the API for Sharing Timetable with Friends. The endpoints for Vellore and Chennai are currenly separate but similar. 

I want to combine the two so that a Vellore campus student would be able to share his/her timetable with his/her Chennai campus friend or vice-versa. If you guys do not want this to be possible, please let me know as soon as possible. 

To do this, I'll be combining the two into one single set of endpoints. And the Token will be used to check if the student is Vellore or Chennai. If RegNo & DoB are used, there will be an additional HTTP Request parameter, as I have been discouraged to use the RegNo directly to find the campus.

**Comment by karthikb351** [comment]
This will be a nightmare to handle since they might be having two different timetable formats. Vellore has new slots like H.

**Comment by aneesh-neelam** [comment]
First off, do we let a Vellore student share his/her timetable with a Chennai student or vice-versa? If no, then nothing more needs to be done. 

If yes, and you want to maintain two separate endpoints for this, this must be implemented in the client itself. When sharing token, also give an option of the campus so that the client will know which endpoint to call. 

Still a nightmare on the client side, I suppose? By mixing both campuses...

**Comment by aneesh-neelam** [comment]
I've kept the URI's seperate, however from the client's point of view it is possible and quite easy to allow Vellore and Chennai students to share timetables with each other. Its even easier in the [development](https://github.com/aneesh-neelam/VITacademics/tree/development) branch.
