### ISSUE TITLE
I have a requirement !

### ISSUE THREAD

**Issue by eraisedtox** [aneesh-neelam/VITacademics#140]
I wanna have some more info from api , like , having details of course material uploads by faculties..
Is it present?

**Comment by ayushagarwal95** [comment]
No, there is no information about the course material uploaded by faculty as we operate using Parent Login and not Student Login. Course Page is not available on Parent Login.

**Comment by prafulSingh** [comment]
okay.., Is there a way around..,I mean what can I do if I want that ? Can I create my own API? if yes..,then how?

**Comment by eraisedtox** [comment]
okay.., Is there a way around..,I mean what can I do if I want that ? Can I create my own API? if yes..,then how?
