### ISSUE TITLE
Captcha Parsing

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#2]
Automated parsing of the captcha during login needs to be implemented. @karthikb351 

Oh and by the way, I am allowing you can edit only the following files for this particular feature: 
[this](https://github.com/aneesh-neelam/VITacademics/blob/master/api/vellore/login/captcha.js) and [this](https://github.com/aneesh-neelam/VITacademics/blob/master/package.json)
:-P

**Comment by aneesh-neelam** [comment]
OK, I've been researching this. 

The Captcha is in a standard Node.js Buffer. You can find out more about Node.js Buffers from [here](http://nodejs.org/api/buffer.html). Hence you can extract the data bitwise using the Node.js Buffer API. 

Or, you can use a library to extract the pixel data. I've seen: 
- [get-pixels](https://github.com/mikolalysenko/get-pixels)
- [node-bitmap](https://github.com/nowelium/node-bitmap)
- [lwip](https://github.com/EyalAr/lwip)
- [gm](https://github.com/aheckmann/gm)

Check them out, @karthikb351. Although not all of them are applicable or feasible.

**Comment by aneesh-neelam** [comment]
OK, using the [Node.js Buffer Library](http://nodejs.org/api/buffer.html), we have managed to get the captcha's pixel array from the HTTP response data buffer. 

Now all that is left, is matching the pixels with the mask of each character. @karthikb351 

Check [this](https://github.com/aneesh-neelam/VITacademics/blob/captcha-auto/api/vellore/login/captcha.js) out for the latest developments, until it is merged with the [master](https://github.com/aneesh-neelam/VITacademics/blob/master/api/vellore/login/captcha.js) branch.

**Comment by karthikb351** [comment]
Captcha parser has it's own repository now. Easier for me to track and maintain.

Let's move this discussion [here](https://github.com/karthikb351/CaptchaParser/issues)?.

**Comment by aneesh-neelam** [comment]
OK, but please get it done as quickly as possible. It's close to completion.

**Comment by aneesh-neelam** [comment]
Not closed until the Captcha Parser is integrated into VITacademics.

**Comment by aneesh-neelam** [comment]
Hey, its is being integrated [here](https://github.com/aneesh-neelam/VITacademics/blob/captcha-auto/api/vellore/login/captcha-parser.js), on the [captcha-auto](https://github.com/aneesh-neelam/VITacademics/tree/captcha-auto) branch.

**Comment by karthikb351** [comment]
It's done boys :dancer: 

d34bea7da5ae823f811e94ce5c1cad176bbfc2be

**Comment by aneesh-neelam** [comment]
It's ready. Both Vellore and Chennai campuses are now fully functional, with automated Captcha Parsing. Updated Backend deployed to [dev](http://vitacademics-dev.herokuapp.com) and [rel](http://vitacademics-rel.herokuapp.com). 

Check updated [API Documentation](https://github.com/aneesh-neelam/VITacademics/wiki) when porting client apps to this.
