### ISSUE TITLE
Google Analytics event reporting

### ISSUE THREAD

**Issue by karthikb351** [aneesh-neelam/VITacademics#20]
How about integrating something like this? We can get better stats on usage. Simple Express middleware.

https://github.com/joshleaves/node-ga

We could potentially log custom values like IPs, Regnos, etc

**Comment by aneesh-neelam** [comment]
Yeah, I'll check it out.

**Comment by karthikb351** [comment]
Set up a new property in the Google Analytics Dashboard. You can use this tracking ID for Node

```
UA-38195928-7
```

**Comment by biocross** [comment]
I was thinking, this time we should use Mixpanel Analytics across all our infrastructure. Backend, and frontend, both. 

It's really good, and very useful.

**Comment by saurabhsjoshi** [comment]
Noo let's just use Google Analytics everywhere.

**Comment by biocross** [comment]
Mixpanel Mixpanel! :P

**Comment by aneesh-neelam** [comment]
Added node-ga in 8980c8dd7673b82d5a6511282dcd19293fc937f6, uses Google Analytics for now. Let's see how it works first.

**Comment by karthikb351** [comment]
@aneesh-neelam Use the tracking code I gave you? So we have everything in once place.

**Comment by aneesh-neelam** [comment]
But... I wanna track. :-(

Seriously though, if you want to change the tracking code, just change it in the Heroku environment configuration variables. Do this only for [vitacademics-rel](http://vitacademics-rel.herokuapp.com/) however.
