### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by karthikb351** [aneesh-neelam/VITacademics#22]
@aneesh-neelam, I'll need your help for this.

In order to do a proper load test, can you make an auto captcha endpoint that bundles marks, attendance and timetable together and sends it? I can then run the test on just one endpoint. It makes life a lot easier.

**Comment by karthikb351** [comment]
Before I begin, a big shout out to @Deborah-Digges for doing most of the work. She took some time out for this, so show a little love boys.

### The Swarm

We tested the API using a load testing framework called [Locust](http://locust.io).

We tested on the two most expensive endpoints
- `/api/vellore/login/auto` : Which does fetches the captcha, parses it and logs in the user.
- `/api/vellore/data/first` : Which scrapes all the data for a particular user.

The simulation ran for 15 users making requests to both endpoints(one after the other) every 5-15 seconds.

### The Results

#### Response Times (in milliseconds)

| Method | Name | # requests | Median(ms) | Average(ms) | Min(ms) | Max(ms) | Requests/s |
| --- | --- | --- | --- | --- | --- | --- | --- |
| GET | /api/vellore/data/first | 67 | 15000 | 15198 | 6989 | 25847 | 0.31 |
| GET | /api/vellore/login/auto | 73 | 17000 | 17228 | 6573 | 27809 | 0.34 |
|  | Total | 140 | 16000 | 16257 | 6573 | 27809 | 0.66 |

#### Response Time Distribution (in milliseconds)

| Name | # requests | 50% | 66% | 75% | 80% | 90% | 95% | 98% | 99% | 100% |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| GET /api/vellore/data/first | 67 | 15000 | 17000 | 18000 | 19000 | 21000 | 25000 | 26000 | 26000 | 25847 |
| GET /api/vellore/login/auto | 73 | 17000 | 19000 | 20000 | 21000 | 22000 | 25000 | 27000 | 28000 | 27809 |
| Total | 140 | 16000 | 18000 | 19000 | 20000 | 22000 | 25000 | 26000 | 27000 | 27809 |

### The Takeaway

We tried running it for a higher number of users, but after around 17 users, the server was throwing a `503 - Service unavailable`, which led me to believe the server was crashing. After looking at the logs though, the issue seems to be that VIT is taking too long to respond when there are too many concurrent requests.

These tests are obviously worst case, on the `/api/vellore/data/refresh` endpoint, it should be a little faster.

The load testing tool is super simple at this point, only looking at the worst case. I shall write a more realistic one and take a larger sample size. 

Other than that, auto-captcha works like a charm. The server scales well and all bottlenecks now lie at VIT. We are good to go on our end.

**Comment by aneesh-neelam** [comment]
Thanks @Deborah-Digges, this is brilliant. 

However, @karthikb351 do check the performance of just the Node.js application hosted on Heroku and MongoDB hosted on MongoLab. You can do `/friends/share` and/or `/friends/regenerate`

Also, `/data/refresh` endpoint is being changed as outlined in #21.
