### ISSUE TITLE
Documentation and Wiki

### ISSUE THREAD

**Issue by karthikb351** [aneesh-neelam/VITacademics#24]
We need to explain the control/flow for this API so are all clear.
- Endpoints to hit, in what order.
- Expected JSON responses from each endpoint.

**Comment by aneesh-neelam** [comment]
What, [this](https://github.com/aneesh-neelam/VITacademics/wiki) isn't enough? 

Anyway, sample output data is required. A lot of changes have been made and [this](https://github.com/aneesh-neelam/VITacademics/tree/master/api/sample-data) hasn't been updated to reflect those changes.

**Comment by karthikb351** [comment]
If it's there, good. Let's just put it all in the wiki basically.

**Comment by aneesh-neelam** [comment]
Some changes are required. Feel free to edit the Wiki or modify the sample data.

**Comment by aneesh-neelam** [comment]
We need documentation regarding the following: 
- Contributor Guidelines
- Code Style and Quality
- Features that are yet to be implemented

@karthikb351: Anything else?

**Comment by aneesh-neelam** [comment]
Need to update documentation. Now that /advisor and /register endpoints are also present.

**Comment by ayushagarwal95** [comment]
Okay.

**Comment by VinayGupta23** [comment]
Wait I thought /register was removed. What does it do?

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
/register is for the the VITacademics app on the device to register with the API Web Server and Worker for background push notifications and cloud messaging.

**Comment by VinayGupta23** [comment]
Oh alright.

Btw I have a doubt. Sorry its off topic.

For contributors, I comes in the system call right?
And how should I refresh it? Or I shouldn't?

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Just call /system to refresh. The System endpoint is for that only, check if server is up, get messages and contributors.

**Comment by VinayGupta23** [comment]
Alright.
No but should I refresh contributors only once or how frequently do you want me to do it?

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Do what the Android app does, call /system on every refresh. Check out [these few lines of code](https://github.com/saurabhsjoshi/VITacademics-for-Android/blob/master/app/src/main/java/com/karthikb351/vitinfo2/activity/MainActivity.java#L206).

**Comment by ayushagarwal95** [comment]
The API is documented quite decently now, any changes made are also being documented.
