### ISSUE TITLE
Web App

### ISSUE THREAD

**Issue by karthikb351** [aneesh-neelam/VITacademics#26]
This is something we haven't really discussed. Are we going ahead and making a webapp for this? Node can handle it easily.

Edit: Follow development at [VITacademics for Web](https://github.com/karthikb351/VITacademics-for-Web)
I'll update this issue when required.

**Comment by aneesh-neelam** [comment]
OK, you want to do something similar to GCDC, or something else? Like using AngularJS or Polymer?

**Comment by karthikb351** [comment]
AngJS will be the right way of doing it. It'll use the same API as the other client apps. NodeJS will only host it.

**Comment by aneesh-neelam** [comment]
Let's do AngularJS + Polymer. :-D
And @karthikb351, I'll need you to take charge for this. I do not know WebApps well enough. 

Why don't we get some juniors on this?

**Comment by aneesh-neelam** [comment]
@kishore-narendran, @ayushagarwal95 and I, @aneesh-neelam are going to do this. 
Angular.js + Bootstrap fine?

**Comment by aneesh-neelam** [comment]
@ayushagarwal95: I need the landing page, send Pull Request as soon as possible.

**Comment by aneesh-neelam** [comment]
The initial preview of the web app is deployed [here](https://vitacademics-web.herokuapp.com/).

**Comment by biocross** [comment]
Awesome!

**Comment by aneesh-neelam** [comment]
Web App is being developed separately.
