### ISSUE TITLE
Using a single router instance for the entire app

### ISSUE THREAD

**Issue by ghost** [aneesh-neelam/VITacademics#34]
I see that you create a new router instance for every route how about create a single router instance in app.js and use it for all the routes i have done this in my latest commit to the forked repo check it out
https://github.com/aashrairavooru/VITacademics/commit/13dd4acf5b6daf96983aa2b133f79f75c1c062f7

**Comment by aneesh-neelam** [comment]
I'm sorry, I have been unavailable for a while. 
Anyway, what are you talking about and what are you proposing?

**Comment by ghost** [comment]
you are using a seperate router instance for every route that you are using instead you can use a single router in your app.js and pass to all your routes as an argument check out app.js in my fork you will get what i am talking about

**Comment by aneesh-neelam** [comment]
I'm sorry, but that's not how it works. I'm simply creating different files for each route, thats all. 
What you're suggesting to do is no different than how it is now. It is just a change in syntax.
