### ISSUE TITLE
Client App Push Notifications + Job Queues

### ISSUE THREAD

**Issue by karthikb351** [aneesh-neelam/VITacademics#40]
Register and tie GCM ids to users and implement job queues to dispatch notifications to select clients.

**Comment by aneesh-neelam** [comment]
Need an endpoint, called when the user logins to the app on the device. (/api/v2/{campus}/register). 

Will be called only once.

**Comment by ayushagarwal95** [comment]
Could you tell me again as to what is this end point supposed to store in our database?

**Comment by aneesh-neelam** [comment]
@ayushagarwal95: Will get back to you tomorrow.
