### ISSUE TITLE
Privacy issue with token system

### ISSUE THREAD

**Issue by karthikb351** [aneesh-neelam/VITacademics#43]
When exchanging the token for timetable data at `/api/{campus}/friends/share?token={token}`, we should do a simple check of requesting for the user's regno and dob as well so we know who has pulled who's data.

**Comment by aneesh-neelam** [comment]
That's actually a privacy issue. Not a security one. 

But I get why it is a good thing to do, it'll be done in the next major release. I'm sorry, but this will break the API.

**Comment by karthikb351** [comment]
For now build it on dev?
And we should really start having a versioning for our API if it's subject to so many changes so frequently.
My suggestion would be to move to a `/api/v1.1/{campus}/` naming schema so we can keep legacy support easily.

**Comment by aneesh-neelam** [comment]
The latest development branch is always deployed on dev. The latest release branch is deployed on rel. 

About the versioning, let me see what I can do.

**Comment by aneesh-neelam** [comment]
API Versioning implemented in f1f229328862d7dc9669ddc9b6aff79884df3020. Deployed to [vitacademics-dev](https://vitacademics-dev.herokuapp.com/)

**Comment by aneesh-neelam** [comment]
Let's implement this as the first use case for Push Notifications, shall we?

**Comment by karthikb351** [comment]
Push is still pending. We need to get that worker process ready so we can actually implement all of this.

**Comment by aneesh-neelam** [comment]
Alright, but this is the easiest use case for implementing Push Notifications. 

Let's start with this is what I'm saying.

**Comment by aneesh-neelam** [comment]
Done! 
@ayushagarwal95: Need to update API Reference
