### ISSUE TITLE
Enums for courses, marks

### ISSUE THREAD

**Issue by karthikb351** [aneesh-neelam/VITacademics#44]
Right now, our courses list gives a heterogenous list of courses, and there is no standard way for identifying which course type it is.

We should have an enumerated list of course types, and add it as a key for each course so we have a standard way of identifying them.

We should do the same thing for marks.

**Comment by aneesh-neelam** [comment]
Implemented in 46d2e2f70d3a6a19282a1f32d16dbb5345a6929b. Please verify the [vitacademics-dev](http://vitacademics-dev.herokuapp.com) and see if it works fine.

**Comment by aneesh-neelam** [comment]
Done. 
Both course_type and marks_type present. 
Reopen if necessary.
