### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by karthikb351** [aneesh-neelam/VITacademics#46]
``` json

{
    "reg_no": "11BCE0354",
    "dob": "28011993",
    "campus": "vellore",
    "status": {
        "message": "Successful execution",
        "code": 0
    }
}
```
- Status messages should be top level since they are always excepted to exist.
- The relevant data should be within a `data` or `results` key.
#### Something like this

``` json
{
    "message": "Successful execution",
    "code": 0,
    "data": {
        "reg_no": "11BCE0354",
        "dob": "28011993",
        "campus": "vellore"
    }
}
```

The reason for this is, it's more intuitive and allows you to have a cleaner deserialisation process.
`JSON -> Extract and check status -> proceed with parsing`

**Comment by aneesh-neelam** [comment]
No.
