### ISSUE TITLE
Attendance Details Date

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#49]
The Attendance Details are in a plain String format, directly parsed from the HTML. Can be converted to native Time format maybe?

**Comment by aneesh-neelam** [comment]
OK, the HTML from VIT's website shows: "13-Jan-2015". 
The backend will parse that and now show "Tue Jan 13 2015". 

That fine?

**Comment by aneesh-neelam** [comment]
Implemented in 468ae452e5b9dab6bafaf7bdf805d83a0c6ba748.

**Comment by karthikb351** [comment]
The [ISO 8601](http://www.w3.org/TR/NOTE-datetime) format.
It's  `YYYY-MM-DD`

**Comment by aneesh-neelam** [comment]
Gee, thanks @karthikb351.
