### ISSUE TITLE
Cache expiry headers

### ISSUE THREAD

**Issue by ghost** [aneesh-neelam/VITacademics#54]
can cache headers be sent wih the api calls, the clients can cache the requests accordingly,Retrofit also has inbuilt support for cacheing based on cache headers @karthikb351 @aneesh-neelam

**Comment by karthikb351** [comment]
We aren't making those many URL calls for this to be useful

**Comment by ghost** [comment]
Using the cache headers will reduce the amount of work we need to write our
own sqlite wrapper, we anyways need to use cached content when offline
On Mar 20, 2015 5:00 PM, "Karthik Balakrishnan" notifications@github.com
wrote:

We aren't making those many URL calls for this to be useful

**Comment by aneesh-neelam** [comment]
I'm sorry, what? 

Are you talking about [this](https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers).

**Comment by karthikb351** [comment]
@aashrairavooru I agree, but we need a database for other things anyway.

**Comment by aneesh-neelam** [comment]
What are you guys talking about?

**Comment by ghost** [comment]
Cache control headers @aneesh-neelam

**Comment by karthikb351** [comment]
Parked for later.
