### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#55]
Move the cache that stores Cookie and Token from [node-cache](https://github.com/ptarjan/node-cache) to an external server like Redis or Memcached.

**Comment by karthikb351** [comment]
Why? In-process cache is fine right?

**Comment by aneesh-neelam** [comment]
Doesn't scale to multiple processes. And the cache is destroyed when the server is restarted.

**Comment by aneesh-neelam** [comment]
Parked for now. Will increase latency exponentially.
