### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#56]
Now that VITacademics has been running on [io.js](https://iojs.org/en/index.html) successfully for a few weeks, I suppose its time to move on to the newer [JavaScript ECMA-262 specification](http://www.ecma-international.org/publications/standards/Ecma-262.htm). 

This will obviously be a rather exploratory process. Conversion shall only happen where it is beneficial or applicable, not for the sake of conversion itself. 

Check out the supported ES6 features [here](https://iojs.org/en/es6.html).

**Comment by ghost** [comment]
is there a dependency on io.js for this , node versions>0.11 support es6 goodness under the harmony flag doesn't it

**Comment by aneesh-neelam** [comment]
[io.js](https://iojs.org/en/index.html) uses a newer version of V8 than what [Node.js](https://nodejs.org/) uses. 

The ES6 features marked as stable by the [V8](https://developers.google.com/v8/) team are enabled automatically by [io.js](https://iojs.org/en/index.html). Whereas [Node.js](https://nodejs.org/) has all of them (stable and otherwise) under the `--harmony` flag. 

Please read all the information on [this page](https://iojs.org/en/es6.html) first.
