### ISSUE TITLE
Semester Wise Grades

### ISSUE THREAD

**Issue by kishore-narendran** [aneesh-neelam/VITacademics#59]
Find Semester-wise GPA, from Grades Parsing done in #57, Issue #36.

**Comment by aneesh-neelam** [comment]
@kishore-narendran: Grades and Semester-wise GPA is now complete in ddab655719a08e7d6aa1768aadaa877dbd1ab0e5. Check out the sample data [here](https://github.com/aneesh-neelam/VITacademics/blob/ddab655719a08e7d6aa1768aadaa877dbd1ab0e5/api/sample-data/api-grades-success.json).
