### ISSUE TITLE
Application Performance & Error Monitoring and Log Management

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#6]
Must add
[New Relic](https://newrelic.com/) support
[Logentires](https://logentries.com/) support

To both
[Development](http://vitacademics-dev.herokuapp.com/)
[Release](http://vitacademics-rel.herokuapp.com/)

For a full fledged dashboard for the applications' performance and error monitoring

Also, for a log management system for both the hosted applications

**Comment by aneesh-neelam** [comment]
Added [New Relic](https://newrelic.com/) and [Logentires](https://logentries.com/) support in commits: 
6be8b14cb3ed38eac77921d390ccb4e35547d269
65a05403e4e329baf7acf84028e751a9cd55776e
9e2a0fc10b607dcc6ce3258e811d82beab853b53
c1297288fccd24c62d0e71a9d81368ca1ab4c7e6
d6d12af2830aae09a38f9382036bf60d100c5454
a663efe78214385a2b453b2eb5359d6ebfbd79ae
952cbb825ae3f8a0cbbff6147fc6407873f44b98
945c9a68b62255d1d3d934fc47a11065e34e4a1c

**Comment by biocross** [comment]
Beautiful.
