### ISSUE TITLE
Error on calling v2 Vellore API

### ISSUE THREAD

**Issue by biocross** [aneesh-neelam/VITacademics#60]
The response reads: 

`
Cannot read property 'toUpperCase' of undefined
`

I have passed both regno, and dob parameters in POST.

**Comment by karthikb351** [comment]
It's `reg_no` and `dob`

**Comment by biocross** [comment]
The documentation says it's 'regno'. Also, it seems to work fine from XCode, while it doesn't work on POSTMAN

**Comment by aneesh-neelam** [comment]
Use curl, as documented on the Wiki. I think you aren't using Postman correctly.

**Comment by biocross** [comment]
It seems to work now. Alright.
