### ISSUE TITLE
What have you guys done?

### ISSUE THREAD

**Issue by biocross** [aneesh-neelam/VITacademics#61]
I am moving from the legacy API, and some of the changes you guys have done are just plain stupid.

I mean: 

Class number is a now an integer - WTF?
Course_type is an Integer -  What in the world?
Unnecesarily changed the date format in the Attendance Details

What are you guys thinking?

**Comment by aneesh-neelam** [comment]
Keep calm and move to API-v2.

**Comment by karthikb351** [comment]
This probably warrants some more discussion. Slack please?
