### ISSUE TITLE
Faculty Information

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#63]
Scrape faculty information from Student Login and store it in our database. 

Unfortunately, this means we'll have to manually update this information as VITacademics doesn't go into Student Login as of now.

**Comment by kishore-narendran** [comment]
I will get you this if you'd like.

**Comment by aneesh-neelam** [comment]
Unless you're going to get it from the VIT Administration, let @ayushagarwal95 do this.

**Comment by kishore-narendran** [comment]
That is what my plan was? It would be more comprehensive.

**Comment by rahulkapoor90** [comment]
Faculty information like cabin no, email id? I have that.

**Comment by aneesh-neelam** [comment]
@kishore-narendran: Could you send this data to me?

**Comment by kishore-narendran** [comment]
Will do. 

-----Original Message-----

**Comment by aneesh-neelam** [comment]
@kishore-narendran: Please send this data.

**Comment by aneesh-neelam** [comment]
Need an endpoint for this.

**Comment by ayushagarwal95** [comment]
The endpoint has been made. Unit tests (if we can have any for this) and testing is left.

**Comment by aneesh-neelam** [comment]
Put Senthil as a test faculty when querying endpoint :-P

**Comment by ayushagarwal95** [comment]
This is done.
