### ISSUE TITLE
[Priority] Hitting MongoDB size limits on Mongolab

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#65]
We don't have any problem now, but we may face one next semester. As of right now, we have 11467 unique users from both Vellore and Chennai campuses, the MongoDB database is using around1008 MB of disk space and the size of the data is 323 MB. 

![Alt text](https://dl.pushbulletusercontent.com/xAzqyUUMLnQxhKlFYxWPQUtubaNLYm6W/Capture.PNG)

On the free plan, we have a 512 MB size limit. Right now, we don't need to do anything, but it could be a problem in the future.

**Comment by kishore-narendran** [comment]
What about dumping the data, every semester?

**Comment by aneesh-neelam** [comment]
We're anyway dumping the data every semester. 

We can only support another 6000 users or so. We'll have to store less data per user or split into multiple databases if and when that occurs.

**Comment by kishore-narendran** [comment]
What about splitting the data such that the attendance data is maintained separately?

**Comment by aneesh-neelam** [comment]
That is one solution. Let's park this for now. I highly doubt we'll have 6000 new users overnight.

**Comment by aneesh-neelam** [comment]
OK, it is a more urgent problem than I thought. 

![Alt text](https://dl.pushbulletusercontent.com/pTAqRccggPWyMsRF6D69M0BkVaHaVHc0/Screenshot%20from%202015-04-02%2021:53:21.png)

However, it is now solved.
