### ISSUE TITLE
'Subject Type' in API Response

### ISSUE THREAD

**Issue by biocross** [aneesh-neelam/VITacademics#67]
There's no key in the response that specifies if the subject is an "Embedded Theory", "Lab Only" etc.

There's a subject type key, which returns integers, but I can't find any information on what each number maps to in the documentation.

**Comment by aneesh-neelam** [comment]
Course Type is present in a key called "course_type". It has the following values: 
- CBL Course: 1
- LBC Course: 2
- PBL Course: 3
- RBL Course: 4
- PBC Course with specific information (like Project Title, Guide): 5
- PBC Course with no such information: 6
- Unsupported Course Type: 0

Similarly, Marks Type is present in a key called "marks_type". It has the following values: 
- CBL Type: 1
- LBC Type: 2
- PBC Type: 3
- PBL/RBL Type: 4
- Unsupported Marks Type: 0

**Comment by biocross** [comment]
Okay, but then how do I get information like "Embedded Theory" and stuff?

**Comment by aneesh-neelam** [comment]
You can't, at least not now. Why do you need it?

**Comment by biocross** [comment]
It's an important information to show. And it's readily available on the academics website.

**Comment by aneesh-neelam** [comment]
OK, I'll add it. The key will be "subject_type". Fine?

**Comment by biocross** [comment]
Thanks :)

**Comment by aneesh-neelam** [comment]
@biocross: "subject_type" added in 32441fc6123feb87e957106bd0ad69c180525ac1. Check sample data [here](https://github.com/aneesh-neelam/VITacademics/blob/32441fc6123feb87e957106bd0ad69c180525ac1/api/sample-data/api-data-refresh_success.json).

**Comment by VinayGupta23** [comment]
Is there sample data available for RBL and PBC courses?

**Comment by aneesh-neelam** [comment]
@ayushagarwal95 will send you the details of people who have RBL and PBC courses via private message.
