### ISSUE TITLE
Incorrect class timings for Chennai Campus

### ISSUE THREAD

**Issue by VinayGupta23** [aneesh-neelam/VITacademics#76]
It has been brought to notice that Chennai Campus students have slightly different class timings, that differ from the general timetable of Vellore students.
Owing to this, incorrect timings are being displayed for Chennai students using the client apps. A screenshot of their timetable is attached for reference.

![time table](https://cloud.githubusercontent.com/assets/8874825/7105451/a0dcbc9e-e137-11e4-97df-f2d22bc9caa1.JPG)

**Comment by ayushagarwal95** [comment]
Their timetable format and timings are different which was not known. It will be fixed soon.

**Comment by VinayGupta23** [comment]
Sure.
Also, client permissions have been taken, to use the following credentials for testing:

14MMT1019
19061993
chennai

If required, this can be added to the list of test credentials.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Fixed in 6352de5fcdc28295e4cf8bb9059f50a77aeb9f53.

**Comment by aneesh-neelam** [comment]
There is a problem with the fix in 6352de5fcdc28295e4cf8bb9059f50a77aeb9f53, but was quickly rectified. 
@ayushagarwal95: Issue Pull Request as soon as possible.
