### ISSUE TITLE
[Priority] API needs phone number as second password

### ISSUE THREAD

**Issue by kishore-narendran** [aneesh-neelam/VITacademics#79]
They've added Parent Mobile Number.

**Comment by VinayGupta23** [comment]
Yes. That was so ... hopeless.
Im already receiving complaint mails.

So until this is fixed, ALL apps will remain dysfunctional.

Sent from my Windows Phone

**Comment by biocross** [comment]
Hopefully it won't be so hard to implement, as it's just another field. I'll push an update to the iOS app today itself.

**Comment by aneesh-neelam** [comment]
You guys should really calm down. 

Look at the Android app, it hasn't been working properly for 4 months now. You don't see @karthikb351 panicking. 

Will fix this for API v2 soon.

**Comment by VinayGupta23** [comment]
Uh lol.
Sure. 👍

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Since this is a high priority bug, I'll be deploying the latest Development build as soon as it passes all tests.

**Comment by aneesh-neelam** [comment]
Well, there you go. Now, get cracking with the client apps. Check out the updated JSON API [here](https://github.com/aneesh-neelam/VITacademics/wiki/JSON-API). 

I've also deployed the latest [Development Build](https://github.com/aneesh-neelam/VITacademics/tree/development) to [vitacademics-rel](https://vitacademics-rel.herokuapp.com/).

**Comment by aneesh-neelam** [comment]
For @saurabhsjoshi, @biocross, @kishore-narendran, @karthikb351, @VinayGupta23: 
By the way, mobile number is added only for the Vellore campus parent login. For Chennai campus, you can send a mobile number string but it'll be ignored.

**Comment by biocross** [comment]
iOS app has been updated to 3.1.2 (Build 6) to accomodate this change and has been pushed to Apple for an Expedited Review.
