### ISSUE TITLE
Chennai Backend API

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#8]
The Chennai API must be fully implemented, to be on par with the Vellore one.

**Comment by aneesh-neelam** [comment]
Is Parent Login for the Chennai campus down? It has been for a while. 

This is the right URL right? [Chennai Parent Login](http://27.251.145.3/parent/)

@saurabhsjoshi, @biocross, @karthikb351

**Comment by saurabhsjoshi** [comment]
Yes that is the correct URL and yes it's been down for more than a week now. Even while it was working they had not updated it to show the latest semester details.

**Comment by aneesh-neelam** [comment]
Parent Login for Chennai is still down, and I have not come across any other URLs for it.

**Comment by biocross** [comment]
Wait, we have got the new URL. Someone submitted it in the feedback.

**Comment by saurabhsjoshi** [comment]
Yes new URL is http://27.251.102.132/parent/

**Comment by aneesh-neelam** [comment]
Chennai API is now complete. Implemented in the following commits: 
19c246a43e3f8f1bfd69eeebf66314d1d3df7a0b
fe3741d66454524f371b2094e0fe4704c2452dfe

Updated code deployed to: 
[Development](http://vitacademics-dev.herokuapp.com/)
[Release](http://vitacademics-rel.herokuapp.com/)

Updated the API documentation in the [Project Wiki](https://github.com/aneesh-neelam/VITacademics/wiki)

**However [Parent Login for Chennai campus](http://27.251.102.132/parent) is currently outdated and buggy. Hence for the Chennai campus students, only the previous semester's data sans marks is available at this time**

**Comment by aneesh-neelam** [comment]
Chennai API is working again, they've updated the [Parent Login for Chennai Campus](http://27.251.102.132/parent)

I've also fixed a bug with scraping PBL marks for both Vellore and Chennai when there are multiple PBL courses. Only the first course used to be scraped, now all of them are. All theory courses in Chennai campus are PBL. 

Check out the [API Documentation](https://github.com/aneesh-neelam/VITacademics/wiki) for Chennai campus.
