### ISSUE TITLE
Possible misplaced "chaining" of timings for some courses in Chennai campus

### ISSUE THREAD

**Issue by VinayGupta23** [aneesh-neelam/VITacademics#84]
Well, following from the recent volley of posts about the Chennai campus (why can they not conform with Vellore),
It has come to notice (yet again) that some theory courses have mixed slots but their timings are to be treated like those of a theory course only.

For example, refer to the Json of the course below for a 2-credit CBL course:

``` json
{
            "class_number": 2290,
            "course_code": "JAP101",
            "course_title": "Basic Japanese",
            "subject_type": "Theory Only",
            "ltpc": "2002",
            "course_mode": "CBL",
            "course_option": "Regular",
            "slot": "TG1+L18",
            "venue": "AB702",
            "faculty": "RAVI MEDHANKAR - SSL",
            "registration_status": "Registered and Approved",
            "bill_date": null,
            "bill_number": null,
            "project_title": null,
            "timings": [
                {
                    "day": 2,
                    "start_time": "06:10:00Z",
                    "end_time": "07:50:00Z"
                }
            ],
            "course_type": 1
    }
```

Here, the slot is "TG1+L18".
However, this is a CBL course having ltpc as "2002", which means 2 theory classes.
Also, observing the attendance displayed in the parent login website,
![attendancedata](https://cloud.githubusercontent.com/assets/8874825/7258546/f2ce7e94-e87a-11e4-85a9-86cd78006833.PNG)

Note above that "L18" and "TG1" are treated as individual classes, despite their illusion in the timetable as consecutive classes (see below under Wednesday):
![time table](https://cloud.githubusercontent.com/assets/8874825/7258579/243b7414-e87b-11e4-99a3-e32a55eb7635.JPG)
#### Suggested change

When parsing the timetable, an added condition could be placed to only chain those timings that are tagged as "Lxx".
The required timings for the above course sampled must be ideally:

``` json
"timings": [
                {
                    "day": 2,
                    "start_time": "06:10:00Z",
                    "end_time": "07:00:00Z"
                },
                {
                    "day": 2,
                    "start_time": "07:00:00Z",
                    "end_time": "07:50:00Z"
                }
            ]
```

Since what it really is is a CBL course of 2 credits.

**Comment by aneesh-neelam** [comment]
I am aware of this. This was done on purpose. 
I'm sorry, but this won't be changed.

**Comment by karthikb351** [comment]
What nonsense @aneesh-neelam. This is a legitimate issue. We should design this to work even for such cases.

If you want, park it for now. But don't close.

**Comment by aneesh-neelam** [comment]
Fixing this isn't a problem at all, can do it within minutes. I'm afraid of inconsistency in data. 
After all, we want to have common timings for consecutive slots right? Or is that only for lab slots?

**Comment by VinayGupta23** [comment]
Well the only reason I don't think its alright to have common timings here is because the attendance is uploaded individually for each session.

If we look at the attendance for any lab slot, it shows like this:
Having "class units" of value 2, and slot as "Lx1+Lx2". This means it is meant to be taken together.
But in the other course it says "class units 1" and is CBL.

So I suppose despite the really weird timings, it is still individual classes.
Perhaps we could get a cross check of this with someone at Chennai campus, to ensure if this is how their system works. I could ask the guy who gave me these credentials.

.............
I've attached a photo but I don't know if it gets uploaded via mail.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
The picture hasn't come. Stop using mail, use the GitHub website.

**Comment by VinayGupta23** [comment]
The picture is just an attendance details screenshot from parent login for a lab course.

Hey I know, but Im replying from phone right, not in my room right now.

Sent from my Windows Phone
