### ISSUE TITLE
Switch to the Summer Semester of 2015

### ISSUE THREAD

**Issue by biocross** [aneesh-neelam/VITacademics#86]
Must now use Summer Semester data.

**Comment by aneesh-neelam** [comment]
In the process of doing so. Give me a few days.

**Comment by aneesh-neelam** [comment]
@VinayGupta23: Give me the credentials of people staying back for the Summer Semester 2015, Send them privately, via email, to [me](mailto:neelam.aneesh@gmail.com).

**Comment by VinayGupta23** [comment]
Btw, servers have been dysfunctional since yesterday. Is that due to the switch?

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
@VinayGupta23: What do you mean dysfunctional? What went wrong and when did it happen, I want details.

**Comment by VinayGupta23** [comment]
HttpStatus 503
Service Unavailable

This is happening on all current APIs.
This is sudden and was being experienced since June 1 (Monday) night.

No changes were made to HTTP calls at my end.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Are you getting 503s now? And have you been getting them since then?

**Comment by VinayGupta23** [comment]
Yes I'm getting 503s now.
I checked both from my PC and phone.

I don't know what I would have been getting before, since I only checked the exact code when you asked.
However, my code was (and is) wrapping up the error as a "Server Error" end-user message.
So it must have been the same.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Are you using vitacademics-dev?

**Comment by VinayGupta23** [comment]
Yeah.

Okay I switched to release and it worked fine. So are there some core changes happening in dev?

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
I shut down vitacademics-dev for maintenance. It's annoying to keep track of both Heroku apps. 

Anyway, there are changes, even to the JSON format. I'll keep you posted.

**Comment by aneesh-neelam** [comment]
Also, never use vitacademics-dev unless I tell you to do so. Open that in the browser: https://vitacademics-dev.herokuapp.com/

**Comment by VinayGupta23** [comment]
Oh okay.
Yeah.. Alright.

Sure.
Well for Json changes, I hope at least the basic content pattern is the same and changes mean data types and formatting only :P
Either way, yeah let me know when done.

Okay I'll switch to release for testing the app then now.
Thanks.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Implemented in #90.
