### ISSUE TITLE
Changes to Grades Response Format

### ISSUE THREAD

**Issue by biocross** [aneesh-neelam/VITacademics#93]
The whole point of building the grades features was to display a table in which people could dynamically change grades, and display the resulting CGPA.

Hence,
- Only display the latest instance of the subject, without any history.
- Don't display withdrawn subjects.

Also, I think the GPA, and CGPA calculation should be left to the client apps.

**Comment by aneesh-neelam** [comment]
@VinayGupta23: Your thoughts?

**Comment by kishore-narendran** [comment]
Why don't you filter it out as needed on the client end?

**Comment by biocross** [comment]
Because it'll be a lot of work on the iOS framework I'm using, and also, why do it 3 times on 3 platforms, when it can be done once?

**Comment by aneesh-neelam** [comment]
@kishore-narendran: Because he's very lazy. His actual reasoning was [moment.js](http://momentjs.com/) is easier to use than any DateTime iOS library.

**Comment by biocross** [comment]
That too :P

**Comment by kishore-narendran** [comment]
I thought it was all supposed to be complete. Okay but this shouldn't be a big change.

**Comment by aneesh-neelam** [comment]
It is supposed to be complete and it is complete.

**Comment by VinayGupta23** [comment]
No.
Its perfect as it is.
I've done a lot of research on the grades that are being sent for various students of all performances.

GPA and CGPA change for a semester as per clearance of arrears and re-term-ends. If we get the subjects alone, the calculated grade semester wise may be incorrect.

Also, getting every single detail (like withdrawal and arrear, N etc) is a way for a user to know exactly what he did and how he went about the entire degree. It gives completeness. I believe let the JSON be as is.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
@biocross: You're outvoted. Get cracking on Objective-C.

**Comment by VinayGupta23** [comment]
Making a calculator feature is a client-end implementation.

@aneesh-neelam :P

**Comment by biocross** [comment]
:(

**Comment by aneesh-neelam** [comment]
@biocross: Consistency man. 
Keep calm and code.

**Comment by biocross** [comment]
alrighty then.
