### ISSUE TITLE
Invalid Credentials encountered sometimes

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics#97]
Encountering this even when credentials are correct.

**Comment by aneesh-neelam** [comment]
For example, try to login using incorrect credentials. And then try to login using correct credentials.

**Comment by ayushagarwal95** [comment]
Could you send me the credentials you were trying?

I am unable to replicate the error here.

**Comment by VinayGupta23** [comment]
Actually, even I haven't faced such an issue on the Windows app until now.

Maybe it was coincidental.

Also, when I was doing the windows app there was an issue with web pages being cached in the phone itself, due to which the calls were not made everytime. Hence I had to turn that off in the class library. Maybe there could have been a caching problem.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
@VinayGupta23: Until now?

**Comment by VinayGupta23** [comment]
No not in that sense.
As in I haven't faced such an issue.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
@karthikb351: Does [Retrofit](https://square.github.io/retrofit/) do any caching on Android? That would explain this because even I have not encountered such a thing until I've started testing the VITacademics Android app.

**Comment by aneesh-neelam** [comment]
@ayushagarwal95: It is irrespective of credentials. It happened with @biocross's credentials, yours and mine.

**Comment by VinayGupta23** [comment]
Well I suppose that makes it more likely it may be a caching issue, if its irrespective of credentials.

Sent from my Windows Phone

**Comment by aneesh-neelam** [comment]
Or it could just be my imagination. @ayushagarwal95: See if this occurs when you use [cURL](http://curl.haxx.se/) or [Postman](https://www.getpostman.com/).

**Comment by VinayGupta23** [comment]
Haha yeah. However, do check it up, many HTTP libraries have caching enabled by default.

**Comment by ayushagarwal95** [comment]
I tried with my own, it didn't occur. I used cURL on the release Heroku application.
